# Generated by Django 6.0.3 on 2026-03-23 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('proficiency', models.IntegerField(help_text='Proficiency of the skill(85%): ')),
            ],
        ),
    ]
