# Generated by Django 6.0.3 on 2026-03-23 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portmidterm', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Portfolio',
            new_name='Skills',
        ),
    ]
